### ISSUE TITLE
The preprocessed datasets and their labels can not be accessed.

### ISSUE THREAD

**Issue by mazicwong** [shamanez/BERT-like-is-All-You-Need#1]
Hi, thank you for your open-source.

However, I find the preprocessed dataset google drive is deprecated:

```
The preprocessed datasets and their labels can be found in the this google drive.
```

Can you provide a new address? Thanks!

**Comment by shamanez** [comment]
Hi thank you for showing the interest. I will upload all the preprocessing
dataset to the cloud as soon as possible. The problem is I am not in my lab
and my internet connection is very slow.


Which dataset you need ?

All three of them ?

**Comment by mazicwong** [comment]
Hi, I need all of them.

thanks a lot!

**Comment by XiaoqiJiao** [comment]
Hi, shamanez. I intend to reproduce the results in your paper. But can't get the preprocessed datasets and labels. Can you provide a  new link? or send them to my email if possible.

**Comment by shamanez** [comment]
Good News data being uploaded :) 

Might take at least a day. My free Gdrive is super slow.

Also, my home connection is not good :) 
So just wait for maximum 48 hrs :) 

Cheers!

**Comment by mazicwong** [comment]
> Good News data being uploaded :)
> 
> Might take at least a day. My free Gdrive is super slow.
> 
> Also, my home connection is not good :)
> So just wait for maximum 48 hrs :)
> 
> Cheers!

thanks!

**Comment by shamanez** [comment]
data and labels are there in the link. Cheers!
