### ISSUE TITLE
envrionment information and training commands of other datasets

### ISSUE THREAD

**Issue by melodymelodymelody** [shamanez/BERT-like-is-All-You-Need#10]
I have read your paper carefully and your work is great. Can you publish the version information of the code environment and the training commands details of the datasets  mosi and mosei?

**Comment by shamanez** [comment]
Hi ,

It is in the README (check useful commands and below).  I used Fairseq at that time. I actually do not remember the version and I have lost the virtual environment details. But you can install them from sources.

**Comment by melodymelodymelody** [comment]
Thanks for your quick response! I see the training command of iemocap dataset in the README.md. So  the training command of other datasets is same as the iemocap dataset?

**Comment by shamanez** [comment]
yeah, you just need to change the dataset path and task.

**Comment by melodymelodymelody** [comment]
Thank you for your detailed answer！

**Comment by shamanez** [comment]
@melodymelodymelody 

![image](https://user-images.githubusercontent.com/16892570/111028190-f8705800-8459-11eb-99f0-a19faf861f78.png)
