### ISSUE TITLE
Why only use the data of dimension 0?

### ISSUE THREAD

**Issue by FriedaSmith** [shamanez/BERT-like-is-All-You-Need#12]
Why only use the data of dimension **0**? Is it because this dimension is a deep features, while other dimensions are not？
```
            j_aud_n=x_a[:, 0, :]
            ...
            j_text=x_t[:, 0, :] #text embeddigs

```

**Comment by shamanez** [comment]
Because we  CLS token is the first token. Usually, this token aggregates information in the entire sequence. You can read about CLS token in BERT.

**Comment by FriedaSmith** [comment]
Thanks
