### ISSUE TITLE
Fusion

### ISSUE THREAD

**Issue by mahsaShafaei** [shamanez/BERT-like-is-All-You-Need#13]
In the paper, two methods are introduced for fusion: shallow fusion (concatenation) and co-attention. In the code how can I switch to these methods? what is the default method in the code?

**Comment by shamanez** [comment]
Hi,

you can change this script to switch between two fusion methods. 

https://github.com/shamanez/BERT-like-is-All-You-Need/blob/master/fairseq/modules/transformer_multi_encoder.py#L184
