### ISSUE TITLE
CUDA out of memory when trying to train on MOSI dataset

### ISSUE THREAD

**Issue by shuangwei123** [shamanez/BERT-like-is-All-You-Need#14]
Hi, thanks for sharing your code.

I want to reproduce your result and is training your model on MOSI dataset, and here is my command modified based on the IEMOCAP script you give:

> python train.py --data ./T_data/mosi --restore-file None --task emotion_prediction --reset-optimizer --reset-dataloader --reset-meters --init-token 0 --separator-token 2 --arch robertEMO_large --criterion emotion_prediction_cri --num-classes 1 --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.1 --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-06 --clip-norm 0.0 --lr-scheduler polynomial_decay --lr 1e-05 --total-num-update 10 --warmup-updates 10 --max-epoch 10 --best-checkpoint-metric loss --encoder-attention-heads 2 --batch-size 1 --encoder-layers-cross 1 --no-epoch-checkpoints --update-freq 1 --find-unused-parameters --ddp-backend=no_c10d --regression-target-mos --a-only --t-only --pooler-dropout 0.1 --log-interval 1 --data-raw ./mosi-20210325T023959Z-001/mosi/

I'm getting CUDA out of memory issue even with batch_size = 1.

> RuntimeError: CUDA out of memory. Tried to allocate 1.72 GiB (GPU 0; 8.00 GiB total capacity; 5.17 GiB already allocated; 826.32 MiB free; 5.21 GiB reserved in total by PyTorch)

I tried to train it on CPU, but the accuracy seems to be very bad, so I assume there is something wrong with this training script.
And also I am unclear about some of the commands, please provide me some explanation if possible.
1.  I am using '--criterion emotion_prediction_cri' and '--regression-target-mos' for the task. Is this the correct args for classification on MOSI dataset?
2.  how does the arg '--num-classes' work for the MOSI dataset? In your paper, you have binary classification accuracy and 7-class accuracy, and corresponding F-1 score. But when I was training on CPU, there is only one single accuracy.

Thanks in advance,
Shuang

**Comment by shamanez** [comment]
Actually, CMU-MOSI is originally a regression task. Basically, you try to predict the sentiment score. Then that score later divided into 7 classes. 

What is your GPU memory size?

**Comment by shuangwei123** [comment]
Ok, so the CMU-MOSI task is a regression task and the result is then used for classification. So we don't need the arg '--num-classes' in the script? Also, My GPU memory is 8GB.

**Comment by shamanez** [comment]
Yeah. Well I haven't trained with 8gb one. I think at least you need 11gb
one. Also I am not sure with CPU. Maybe you can try newer faiseq things.
