### ISSUE TITLE
Does this repository not contain IEMOCAP with 4-class?

### ISSUE THREAD

**Issue by Chenpuh** [shamanez/BERT-like-is-All-You-Need#18]
How to understand **Binary Accuracy** ? Does this repository not contain **IEMOCAP with 4-class**?

**Comment by shamanez** [comment]
It does contain. Binary accuracy is resting whether each emotion is present
or not. Let's say whether it is happy or not.

**Comment by Chenpuh** [comment]
Is **IEMOCAP with 4-class**  the following code? I don't understand the meaning of this code? It seems to be **Binary Accuracy**, because it's not predicting a single emotion.
```
targets = targets.long()
          
            targets=torch.nn.functional.one_hot(targets, 4)


            logits=logits.view(-1, 2)
            targets= targets.view(-1)

            loss = F.nll_loss(
                F.log_softmax(logits, dim=-1, dtype=torch.float32),
                targets,
                reduction='sum',
            )

            preds = logits.max(dim=1)[1]

            ncorrect=(preds == targets).sum().item()


            # sample_size=sample_size*4


            logging_output = {
                'loss': utils.item(loss.data) if reduce else loss.data,
                'ntokens': sample_size*4,#sample['ntokens'], #sample size only for the trainign phase of the binary iemocap
                'nsentences': sample_size*4, 
                'sample_size': sample_size*4,
                'ncorrect':ncorrect
            }
```

**Comment by Chenpuh** [comment]
@shamanez Can you provide **training command** and **validation command** for **IEMOCAP with 4-class**?

**Comment by shamanez** [comment]
It's there in the README. For IEMOCAP just use the num_cls as 8, since we do binary accuracy.

**Comment by Chenpuh** [comment]
That **num-classes** is 4, is it  **4-class**?

**Comment by shamanez** [comment]
Actually it should be 4.

**Comment by shamanez** [comment]
Sorry 8.. because you predict binary accuracy for each class.

**Comment by Chenpuh** [comment]
When I use the following command, the error appears.

`python train.py --data ./T_data/iemocap ---restore-file None --task emotion_prediction --reset-optimizer --reset-dataloader --reset-meters --init-token 0 --separator-token 2 --arch robertEMO_large --criterion emotion_prediction_cri --num-classes 4 --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.1 --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-06 --clip-norm 0.0 --lr-scheduler polynomial_decay --lr 1e-05 --total-num-update 2760 --warmup-updates 165 --max-epoch 10 --best-checkpoint-metric loss --encoder-attention-heads 2 --batch-size 1 --encoder-layers-cross 1 --no-epoch-checkpoints --update-freq 8 --find-unused-parameters --ddp-backend=no_c10d --binary-target-iemocap --a-only --t-only --pooler-dropout 0.1 --log-interval 1  --data-raw ./iemocap_data/`

The error is as follows
```
Traceback (most recent call last):
  File "/media/other/Code/SER/study/bert_ser/train.py", line 12, in <module>
    cli_main()
  File "/media/other/Code/SER/study/bert_ser/fairseq_cli/train.py", line 361, in cli_main
    main(args)
  File "/media/other/Code/SER/study/bert_ser/fairseq_cli/train.py", line 115, in main
    train(args, trainer, task, epoch_itr)
  File "/media/chen/Application/anaconda3/envs/bert_like/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/media/other/Code/SER/study/bert_ser/fairseq_cli/train.py", line 198, in train
    log_output = trainer.train_step(samples)
  File "/media/chen/Application/anaconda3/envs/bert_like/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/media/other/Code/SER/study/bert_ser/fairseq/trainer.py", line 358, in train_step
    ignore_grad=is_dummy_batch,
  File "/media/other/Code/SER/study/bert_ser/fairseq/tasks/fairseq_task.py", line 340, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/media/chen/Application/anaconda3/envs/bert_like/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/other/Code/SER/study/bert_ser/fairseq/criterions/emotion_prediction_cri.py", line 161, in forward
    reduction='sum',
  File "/media/chen/Application/anaconda3/envs/bert_like/lib/python3.6/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (2) to match target batch_size (4).
```

**Comment by shamanez** [comment]
Change num-classes to 8

**Comment by Chenpuh** [comment]
If you use the following command, it seems a  **binary accuracy** command.

`python train.py --data ./T_data/iemocap ---restore-file None --task emotion_prediction --reset-optimizer --reset-dataloader --reset-meters --init-token 0 --separator-token 2 --arch robertEMO_large --criterion emotion_prediction_cri --num-classes 8 --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.1 --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-06 --clip-norm 0.0 --lr-scheduler polynomial_decay --lr 1e-05 --total-num-update 2760 --warmup-updates 165 --max-epoch 10 --best-checkpoint-metric loss --encoder-attention-heads 2 --batch-size 1 --encoder-layers-cross 1 --no-epoch-checkpoints --update-freq 8 --find-unused-parameters --ddp-backend=no_c10d --binary-target-iemocap --a-only --t-only --pooler-dropout 0.1 --log-interval 1 --data-raw ./iemocap_data/`

Because when I use the following **validation command** to predict emotions, preds may be **[0, 0, 0, 0]** and **[1, 0, 1, 0]** in line 113, **fairseq/criterions/emotion_prediction_cri.py**.

`python validate.py --data ./T_data/iemocap --path './checkpoints/checkpoint_best.pt' --task emotion_prediction --valid-subset test --batch-size 1`

```
            logits=logits.view(-1, 2)
            targets= targets.view(-1)

            loss = F.nll_loss(
                F.log_softmax(logits, dim=-1, dtype=torch.float32),
                targets,
                reduction='sum',
            )

            preds = logits.max(dim=1)[1]

            ncorrect=(preds == targets).sum().item()
```
