### ISSUE TITLE
ValueError: tokens exceeds maximum length: 550 > 512

### ISSUE THREAD

**Issue by Bharath1991999** [shamanez/BERT-like-is-All-You-Need#19]
Getting this error while training because token length exceeds BERT max token length 512
![Screenshot (177)](https://user-images.githubusercontent.com/49364681/115568547-08414e80-a2da-11eb-8778-4cd77acb1090.png)

**Comment by shamanez** [comment]
This is normal. The Roberta model can only take inputs shorter than 512 tokens. You need to shorten those sentences with tokens.

**Comment by Bharath1991999** [comment]
Thanks for replying
If we shorten those sentences. What about corresponding audio files. Should we even shorten them. 
How to do it

**Comment by shamanez** [comment]
Mmm not. Just check if speech bert tokens or Robert tokens from each
example goes over 512. Chunk the examples examples that go over the limit
( only the modality )

**Comment by kruthikakr** [comment]
Hi...Is the SER model files available ? also how to do the inference with the ASR samples ? any reference testing is done other than the datasets ?

**Comment by Bharath1991999** [comment]
Any trained models available with you?

**Comment by shamanez** [comment]
I think I do not have the checkpoints.  also, I did not do with other datasets. But I would suggest you go with similar multimodal fusion mechanism. 

tbh this is almost a year old project, which I used Faiseq.  Now you can use the Huggingface wav2vec2 model and ROBERTA model to re-wamp this project.

cheers!
