### ISSUE TITLE
Use of Pre-trained Speech-BERT

### ISSUE THREAD

**Issue by mingzi151** [shamanez/BERT-like-is-All-You-Need#21]
Hi,

Can you please clarify how the pre-trained Speech-Bert is used in your code?

Correct me if I'm wrong, but it seems you initialise parameters specific to BERT model by using normal distribution (with function init_bert_params in transformer_multi_encoder.py), instead of using pre-trained weights. Pre-trained Speech-BERT does not seem to be downloaded/loaded in your scripts either. 

Many thanks.

Regards.

**Comment by shamanez** [comment]
No I used the pre-trained wav2vec checkpoint.

**Comment by shamanez** [comment]
Check Readme, I have mentioned the file that use to load Roberta and Speech
Bert models. I think you are checking a different modeling file.

**Comment by shamanez** [comment]
Check this file

https://www.github.com/shamanez/BERT-like-is-All-You-Need/tree/master/fairseq%2Fmodels%2Fmult_emo.py

**Comment by mingzi151** [comment]
Hi Shamanez,

Thanks for your prompt response.

So, you are suggesting that self.roberta_vqwav2vec (in mult_emo.py) is actually referring to "Pre-trained Speech-BERT" part (in the README chart)? And self.roberta_vqwav2vec is the fine-tuned in the later stage, together with Pre-trained Roberta, right?

Thanks.

**Comment by shamanez** [comment]
Yes, that is correct.

**Comment by mingzi151** [comment]
Thanks for the clarification, Shamanez.
