### ISSUE TITLE
Incorrect metrics calculation for mosi/mosei

### ISSUE THREAD

**Issue by cyZhu98** [shamanez/BERT-like-is-All-You-Need#25]
Thank you for sharing your great work. I found that the calculation of f1-score  and binary accuracy in your code has a little mistake. Maybe you should flatten the matrix first. The 'ba-accuracy' is the true binary accuracy actually.
add
```python
pred_mos = pred_mos.flatten()
truth_mos = truth_mos.flatten()
```
behind line 352
https://github.com/shamanez/BERT-like-is-All-You-Need/blob/a6ba1f656da40103b3b5398961d18e5fc78e1efb/fairseq/criterions/emotion_prediction_cri.py#L352
there's the results i reproduced
before:
`accuracy 48.171 | binary-accuracy 66.463 | ba-accuracy 88.567 | f1-score 85.829`
after:
`accuracy 48.171 | binary-accuracy 88.567 | ba-accuracy 88.567 | f1-score 88.471`

**Comment by shamanez** [comment]
Actually I took the BA accuracy from another paper 's code.

**Comment by shamanez** [comment]
yes use ba-accuracy not the binaray. There;s a bug :) Thanks
