### ISSUE TITLE
AssertionError: "misalignment of data"

### ISSUE THREAD

**Issue by cuczy** [shamanez/BERT-like-is-All-You-Need#3]
assert items_a[0].split('.')[0] == items_t[0].split('.')[0] , "misalignment of data"
AssertionError: "misalignment of data"
hi!
This problem occurred during the training process.  How can I fix it?
![WechatIMG206](https://user-images.githubusercontent.com/56351074/97793593-03ec8080-1c29-11eb-8b4a-0cc633852b31.png)

**Comment by shamanez** [comment]
Seems like you haven't downloaded the data

**Comment by cuczy** [comment]
I downloaded the data from here
<img width="936" alt="截屏2020-11-01上午10 18 42" src="https://user-images.githubusercontent.com/56351074/97793791-b887a180-1c2b-11eb-97e2-4abe558f273f.png">

**Comment by shamanez** [comment]
Do you have the correct data file addresses on train test and valid?

**Comment by cuczy** [comment]
I put the downloaded data in the root directory of the project file, at the same location as the path you wrote
<img width="936" alt="截屏2020-11-01上午10 33 10" src="https://user-images.githubusercontent.com/56351074/97793931-dce47d80-1c2d-11eb-804f-c7c99e40a910.png">

**Comment by shamanez** [comment]
I think this is a problem with getting the correct data files. Like the data addresses. You will figure it out. Use [these](https://drive.google.com/drive/folders/1toek7wPFvdJehY12akuh9CNf4JkKov30) files to set the addresses (--data argument should contain the address to these files). Actually, you can change the data loader as you need.
