### ISSUE TITLE
pretrained roberta model and dataset size mismatch

### ISSUE THREAD

**Issue by sniperwrb** [shamanez/BERT-like-is-All-You-Need#4]
The pretrained Roberta large has a max_positions=512
while pretrained iemocap-data cross-train has inputs with longer token sequence

**Comment by shamanez** [comment]
Yes, but there are very few such examples. Usually, 512 tokens can handle something around 400 words, and the average time of an IEMOCAP example in something around 3.5 seconds. What you can do is sample such longer sequences randomly. But I do not think there will be a huge accuracy difference.

**Comment by sniperwrb** [comment]
Thanks. This solves my problem.
