### ISSUE TITLE
data

### ISSUE THREAD

**Issue by cn-boop** [shamanez/BERT-like-is-All-You-Need#5]
hello, i am interested in your work. But when I look at your code, I don't find the operation to deal with audio data. And how do you get audio data, I just find corresponding text data in your file folder.

**Comment by shamanez** [comment]
I first get audio wav files and then converted them to embeddings with speech-bert. 

Please refer to [this script](https://github.com/shamanez/BERT-like-is-All-You-Need/tree/master/SPEECH-BERT-TOKENIZATION).
