### ISSUE TITLE
RuntimeError: DataLoader worker (pid 3019) is killed by signal: Killed. 

### ISSUE THREAD

**Issue by 245789064** [shamanez/BERT-like-is-All-You-Need#7]
hello,thank you for your time！I change your   code  ,just use CPU  to run this project .when I load  train data for epoch 1,only load a litte,it send RuntimeError: DataLoader worker (pid 3019) is killed by signal: Killed. But I monitoring my cpu ,there still is 1G space remained.Now,I can not find a way to resolve it .I find you used 2 gpu for training ,I want to know the reaon if I need big space  enough  to train .
![图片](https://user-images.githubusercontent.com/71373667/103995979-2a540c80-51d4-11eb-914e-227efd772ee4.png)

**Comment by 245789064** [comment]
![图片](https://user-images.githubusercontent.com/71373667/103998951-5e7cfc80-51d7-11eb-9035-cf5d2150da63.png)

**Comment by shamanez** [comment]
Seems like a fairseq error.  Sorry I did not try this in a CPU. It worked perfectly for my multi-GPU settings.
