### ISSUE TITLE
You use GPT-2 for raw text preprocessing in your paper .I can not find it in your script.  Can you tell  me which script is for it? Thank you!

### ISSUE THREAD

**Issue by 245789064** [shamanez/BERT-like-is-All-You-Need#8]

**Comment by shamanez** [comment]
I only used gpt-tokenizer. It is the default tokenizer given in the Fairseq.

**Comment by 245789064** [comment]
Can you give it to me ,thank you

**Comment by zhaowil** [comment]
Hi! Have you succeeded in replicating the text preprocessing step? Thank you so much!
